spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/auth2?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
#    hikari:
#      minimum-idle: 5
#      idle-timeout: 600000
#      maximum-pool-size: 10
#      auto-commit: true
#      pool-name: MyHikariCP
#      max-lifetime: 1800000
#      connection-timeout: 30000
#      connection-test-query: SELECT 1
#    type: com.zaxxer.hikari.HikariDataSource
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  type-aliases-package: cn.gjw.mysecurity.domin
  mapper-locations: classpath:mapper/*.xml
