spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useAffectedRows=true&useSSL=false
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    platform: mysql
    #    schema: classpath:/schema.sql
    #第一次启动做建表用，之后注释掉
    type: com.alibaba.druid.pool.DruidDataSource
#    initialization-mode: always
mybatis:
  type-aliases-package: cn.gjw.securityjwt.domain
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
# JWT
jwt:
  header: Authorization
  secret: mySecret
  #token有效期一天
  expiration: 86400
  tokenHead: "Bearer "
server:
  port: 8088
  servlet:
    context-path: /api
