spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
    #    username: root
    #    password: root
    #    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    dynamic:
      primary: db1-master
      datasource:
        db1-master:
          url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
          username: root
          password: root
        db1-slave:
          url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
          username: root
          password: root
        db2-slave:
          url: jdbc:mysql://localhost:3306/test2?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
          username: root
          password: root
  redis:
    host: 193.112.64.183
    port: 6379
    password: 123456


server:
  port: 8082



#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: cn.gjw.mybatisplus2.domain
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.gjw.mybatisplus2.domain
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
  global-config:
    db-config:
      id-type: auto

